# Ultralytics YOLO 🚀, AGPL-3.0 license
"""
Ultralytics modules.

Example:
    Visualize a module with Netron.
    ```python
    from ultralytics.nn.modules import *
    import torch
    import os

    x = torch.ones(1, 128, 40, 40)
    m = Conv(128, 128)
    f = f"{m._get_name()}.onnx"
    torch.onnx.export(m, x, f)
    os.system(f"onnxslim {f} {f} && open {f}")  # pip install onnxslim
    ```
"""

from .block import (
    C1,
    C2,
    C2PSA,
    C3,
    C3TR,
    CIB,
    DFL,
    ELAN1,
    PSA,
    SPP,
    SPPELAN,
    SPPF,
    AConv,
    ADown,
    Attention,
    BNContrastiveHead,
    Bottleneck,
    BottleneckCSP,
    C2f,
    C2fAttn,
    C2fCIB,
    C2fPSA,
    C3Ghost,
    C3k2,
    C3k2_CKA,
    C3x,
    CBFuse,
    CBLinear,
    ContrastiveHead,
    GhostBottleneck,
    HGBlock,
    HGStem,
    ImagePoolingAttn,
    Proto,
    RepC3,
    RepNCSPELAN4,
    RepVGGDW,
    ResNetLayer,
    SCDown,
    UNetV1,
    DWBConv,
    NonLocalBlockND,
    DWBConv_02,
    CKASnet,
    CKACAnet,
    CKAPEnet,
    CKASEnet,
    CKACA_SPDnet,
    SPDConv,
    CKACAnetv2,
    CKASAPE,
    CKAS_IM,
    CKAS_DAF,
    CKAS_PConv,
    DAFusion,
    CKASAPE_75,
    CKASAPE_dili,
    CKASAPE_d,
    CKASAPE_dili_v2,
    CKAS_IM_v3,
    CKAS_IM_v2,
    CKAS_IM_IP,
    CKAS_59,
    CKAS_DAF_V2,
    C2PSA_1,
    C2PSA_1_CondConv,
    C2PSA_1_DCNv1,
    C2PSA_1_DCNv2,
    C2PSA_1_ODConv,
    C2PSA_1_DyConv,
    C2PSA_1_DSConv,
    C2PSA_1_Conv,
    CKABS,
    C2PSA_2,
    C3k2_CKA_2,
    CKAS_DAF_2,
    C2PSA_3,
    C3k2_CKA_3,
    C3k2_CKA_4,
    CKAS_DAF_3x3,
    CKAS_DAF_5x5,
    CKAS_DAF_7x7,
    CKAS_DAF_3_5,
    CKAS_DAF_3_7,
    C2PSA_4,
    MSWAC,
    MSWAC_CondConv,
    MSWAC_DCNv1,
    MSWAC_DCNv2,
    MSWAC_ODConv,
    MSWAC_DyConv,
    MSWAC_DSConv,
    MSWAC_Conv,
    CKAS_DAF_dilation
    
)
from .conv import (
    CBAM,
    ChannelAttention,
    Concat,
    Conv,
    Conv2,
    ConvTranspose,
    DWConv,
    DWConvTranspose2d,
    Focus,
    GhostConv,
    LightConv,
    RepConv,
    SpatialAttention,
    # DWBlocks,
    # DownSample,
    # Stem,
)
from .head import OBB, Classify, Detect, Pose, RTDETRDecoder, Segment, WorldDetect, v10Detect
from .transformer import (
    AIFI,
    MLP,
    DeformableTransformerDecoder,
    DeformableTransformerDecoderLayer,
    LayerNorm2d,
    MLPBlock,
    MSDeformAttn,
    TransformerBlock,
    TransformerEncoderLayer,
    TransformerLayer,
)

__all__ = (
    "Conv",
    "Conv2",
    "LightConv",
    "RepConv",
    "DWConv",
    "DWConvTranspose2d",
    "ConvTranspose",
    "Focus",
    "GhostConv",
    "ChannelAttention",
    "SpatialAttention",
    "CBAM",
    "Concat",
    "TransformerLayer",
    "TransformerBlock",
    "MLPBlock",
    "LayerNorm2d",
    "DFL",
    "HGBlock",
    "HGStem",
    "SPP",
    "SPPF",
    "C1",
    "C2",
    "C3",
    "C2f",
    "C3k2",
    "SCDown",
    "C2fPSA",
    "C2PSA",
    "C2fAttn",
    "C3x",
    "C3TR",
    "C3Ghost",
    "GhostBottleneck",
    "Bottleneck",
    "BottleneckCSP",
    "Proto",
    "Detect",
    "Segment",
    "Pose",
    "Classify",
    "TransformerEncoderLayer",
    "RepC3",
    "RTDETRDecoder",
    "AIFI",
    "DeformableTransformerDecoder",
    "DeformableTransformerDecoderLayer",
    "MSDeformAttn",
    "MLP",
    "ResNetLayer",
    "OBB",
    "WorldDetect",
    "v10Detect",
    "ImagePoolingAttn",
    "ContrastiveHead",
    "BNContrastiveHead",
    "RepNCSPELAN4",
    "ADown",
    "SPPELAN",
    "CBFuse",
    "CBLinear",
    "AConv",
    "ELAN1",
    "RepVGGDW",
    "CIB",
    "C2fCIB",
    "Attention",
    "PSA",
    "UNetV1",
    "CKAS_DAF",
    "NonLocalBlockND",
    "C2PSA_1",
    "C2PSA_1_CondConv",
    "C2PSA_1_DCNv1",
    "C2PSA_1_DCNv2",
    "C2PSA_1_ODConv",
    "C2PSA_1_DyConv",
    "C2PSA_1_DSConv",
    "C2PSA_1_Conv",
    "MSWAC_CondConv",
    "MSWAC_DCNv1",
    "MSWAC_DCNv2",
    "MSWAC_ODConv",
    "MSWAC_DyConv",
    "MSWAC_DSConv",
    "MSWAC_Conv",
)
